### PR TITLE
allow to change namespace on the fly

### PR DESCRIPTION
**Pull request by razum2um**

### CODE REVIEW

**Comment by tubbo** [comment]
@razum2um looks good, can you fix the broken tests?

**Comment by razum2um** [comment]
@tubbo done

**Comment by marceloboeira** [comment]
@razum2um nice, thanks!

**Comment by razum2um** [comment]
@marceloboeira @tubbo could you release this (to write proper dependency in gemspec)

**Comment by razum2um** [comment]
@marceloboeira @tubbo could you also take a look https://github.com/redis-store/redis-activesupport/pull/47 ?

**Pull request merged**
