### PR TITLE
sane default ttl, so it does not hog redis

### PR DESCRIPTION
**Pull request by SamSaffron**
currently there is no default ttl for redis meaning rack cache will hog all of redis, I set up a sane 30 minute default that is tunable

### CODE REVIEW

**Comment by radar** [comment]
Hi @SamSaffron, does this patch still need merging? If so, can you please rebase it against current master?

**Comment by SamSaffron** [comment]
this definitely needs to be done, we moved off redis store about a year ago
cause of this at Discourse.

**Comment by radar** [comment]
@SamSaffron I would be happy to merge this if it was rebased.

**Comment by SamSaffron** [comment]
We no longer use this code base, I am very uncomfortable submitting patches
to code I no longer use

**Comment by tubbo** [comment]
this seems to have been recently fixed upstream in rack-cache and redis-rack-cache.

**Pull request closed without merging**
