### PR TITLE
Redis 5 compatibility fix

### PR DESCRIPTION
**Pull request by PikachuEXE**
I have only fixed the unknown keyword issue (on redis-client)
Still got many other issues that seem to be related to redis-rb 5.x itself

Related: https://github.com/redis-store/redis-store/issues/358

Update 1: Fixed except mainly namespace tests & I have no idea how to fix
Update 2: Fixed all tests (mostly due to `redis.rb` internal changes)

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Fixed most tests except `mapped_mget` which seems to be introduced by https://github.com/redis-store/redis-store/pull/282 
But I don't see any code that can be worked on

**Comment by PikachuEXE** [comment]
@tubbo Hey would you mind reviewing this when you have time?
We have some folks in #358 giving positive feedbacks for this PR already

**Comment by rcugut** [comment]
@PikachuEXE we have your running in production, all tests passed and works fine.
It'd be great to have it merged and released as a new version for redis-store.
Thanks for fixing it!

**Comment by softbrada** [comment]
any updates on this? I really need these also.

**Comment by soumyaray** [comment]
Yep this fix works well for me in dev/production as well.

@softbrada I put the following in my Gemfile for now:
```
gem 'redis-store', git: 'https://github.com/PikachuEXE/redis-store', branch: 'fix/redis-client-compatibility'
```

Then `bundle update`, and use `bundle exec [...]` to run your process

**Comment by PikachuEXE** [comment]
@tubbo Would you have time to review this any time soon?

**Comment by PikachuEXE** [comment]
Is anyone besides @tubbo maintaining this project? (@tubbo seems busy in private repo(s))
Or would anyone with permission to add maintainers consider adding more people to maintain these projects? (`redis-store` related)

**Comment by n-rodriguez** [comment]
Ping @tubbo

**Comment by rorstuff** [comment]
Please merge. Thank you @PikachuEXE

**Comment by gamecreature** [comment]
I've got a lot of projects which are locked to the old version, please merge to support Redis 5. Thanks!

**Comment by MikeMcQuaid** [comment]
> @PikachuEXE could you add more kwargs to remove? `:expires_in` and `:raise_errors`

Unless I'm mistaken: this is a bigger problem. There are both documented as supported options in https://github.com/redis-store/redis-rails#rails-fragment-cache and, if you just remove the kwargs, it's not clear to me that redid-store will behave as expected. I could be completely wrong here and, if so: someone please correct my understanding!

**Comment by PikachuEXE** [comment]
@marekls 
Please where your usage to see if those options should be blocked here or in another library `redis-activesupport`

**Comment by marekls** [comment]
@PikachuEXE
```bash 
  # production.rb
  config.cache_store = :redis_store, ENV.fetch('REDIS_URL', nil), { expires_in: 24.hours, raise_errors: false }
```
But I've decided to remove this gem and use build-in `:redis_cache_store` and everything works fine

**Comment by PikachuEXE** [comment]
https://github.com/redis-store/redis-activesupport is now archived and not needed since rails 5.2.0
So I won't make further changes on this branch for it

**Comment by PikachuEXE** [comment]
Should I consider releasing a fork version until any maintainer come here and got stuff merged...

**Comment by PikachuEXE** [comment]
I have created 
- [Branch for forked gem](https://github.com/PikachuEXE/redis-store/tree/pika-fork/master) (if it's published due to no action in this project)
  Already included this PR & some CI fixes
- [PR for forked gem release preparation](https://github.com/PikachuEXE/redis-store/pull/1)

This forked gem idea is a temporary measure due to lack of actions from maintainers in this project and please treat it that way
If enough people (2-3?) approve this idea (just leave some reaction on this comment to not spam people)
I would publish the forked gem
 (Please review the PR linked above before approving, I don't publish forked gems often)

**Comment by makemp** [comment]
In your change @PikachuEXE I've still got a problem with:
```
ArgumentError: unknown keyword: :expires_in
```
Anyways: thank you for your work.

**Comment by PikachuEXE** [comment]
What do you use that requires `expires_in`?

**Comment by n-rodriguez** [comment]
> What do you use that requires `expires_in`?

I use it to auto expire Devise sessions stored in Redis, but weirdly I don't have any issue with it Oo

**Comment by PikachuEXE** [comment]
I assume you are using `https://github.com/redis-store/redis-actionpack`?
Maybe `expire_after` should be used?
(Oh also does that mean I need to release a forked gem for `redis-actionpack` too...)

**Comment by PikachuEXE** [comment]
Update: [`redis-store-pika`](https://rubygems.org/gems/redis-store-pika) released
It still includes `redis-store.rb` and I want to see if there is a way to make other gems load that file instead of the one in `redis-store` gem
Maybe need to include `redis-store` in `Gemfile` with `require: false` and put it above `gem "redis-store-pika"`?
(Haven't tried yet, please report when you found a way. I will update README in fork branch if there is way)

**Comment by PikachuEXE** [comment]
I got me own app working with these in `Gemfile`
```ruby
gem "redis-store-pika"
gem "redis-store", require: false
gem "redis-rack", ">= 2.1.3"
# 2.1.0 required for rack 2.0.8
gem "redis-actionpack", ">= 2.1.0"
gem "redis", ">= 4.2.1"
```

Please leave reaction if this works for you too
I will put this into README after >=2 confirmation received

**Comment by n-rodriguez** [comment]
@PikachuEXE here my gemfile:

```ruby
group :redis do
  # Redis
  gem 'hiredis'
  gem 'hiredis-client'
  gem 'redis'
  gem 'redis_web_manager', github: 'n-rodriguez/redis_web_manager', branch: 'wip/redis'

  # Cache sessions in redis
  gem 'redis-actionpack'
  gem 'redis-store', github: 'PikachuEXE/redis-store', branch: 'fix/redis-client-compatibility'
end
```

**Comment by n-rodriguez** [comment]
@radar : 

Hi there! Since you're a member of https://github.com/redis-store Github organization can you please add @PikachuEXE as a commiter? @tubbo seems to be busy and this PR starts to be blocking to the point we need to fork to maintain this gem 😢 

Any help would be very appreciated 👍 

Thank you!

**Comment by n-rodriguez** [comment]
@jodosha :

Hi there! Since you're a member of https://github.com/redis-store Github organization can you please add @PikachuEXE as a commiter? @tubbo seems to be busy and this PR starts to be blocking to the point we need to fork to maintain this gem 😢 

Any help would be very appreciated 👍 

Thank you!

**Comment by radar** [comment]
I have added @PikachuEXE as a maintainer to this project on GitHub. I know of their great contributions elsewhere and welcome the contributions here too.

**Comment by radar** [comment]
I am currently away on holiday and so I don’t think I can add @PikachuEXE as a gem owner (I think that’s done through the terminal still?).

I’ll try to do this when I’m back home, and if I’m still prevented I’ll try to coordinate with @jodosha.

**Comment by n-rodriguez** [comment]
> I have added @PikachuEXE as a maintainer to this project on GitHub. I know of their great contributions elsewhere and welcome the contributions here too.
>
> I am currently away on holiday and so I don’t think I can add @PikachuEXE as a gem owner (I think that’s done through the terminal still?).
>
> I’ll try to do this when I’m back home, and if I’m still prevented I’ll try to coordinate with @jodosha.

Many thanks for your help and your diligence 👍 

We have avoided the very well known "forking issue" and that's great 😃

**Comment by n-rodriguez** [comment]
> I assume you are using `https://github.com/redis-store/redis-actionpack`?

Yes



> Maybe `expire_after` should be used?

This reminds this : 

> Fix Redis sessions are never expired in Redis \o/
> 
> This is because "expires_after' does not exist.
> It's either :
> * expire_after
> * expire_in
> * expires_in
> 
> See: https://github.com/redis-store/redis-store/blob/master/lib/redis/store/ttl.rb#L32
> 
> We use "expires_in" to be in phase with ActiveSupport::Cache::RedisCacheStore
> which supports this one only.
> 
> See: https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/redis_cache_store.rb#L143
> 

A commit in a private app where I was mistakenly using `expires_after` which doesn't exist.

**Comment by PikachuEXE** [comment]
The [publish workflow](https://github.com/redis-store/redis-store/blob/master/.github/workflows/publish.yml) seems to be using `RUBYGEMS_API_KEY` which does not require me being gem owner

But I have never used it so not sure

**Comment by PikachuEXE** [comment]
I cannot approve my own PR = cannot merge myself

**Review by radar — APPROVED** [review]

**Comment by radar** [comment]
Checks pass and code LGTM. Thanks!

**Comment by PikachuEXE** [comment]
New version released: https://rubygems.org/gems/redis-store/versions/1.10.0

**Comment by n-rodriguez** [comment]
> New version released: https://rubygems.org/gems/redis-store/versions/1.10.0

you're welcome 👍

**Pull request merged**
