### PR TITLE
Enable cache and move to containerized build

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by tubbo** [comment]
Good stuff, I'm working out the test failure right now on PR #267, but
given that it got to the tests this branch looks like it's gonna pass. I'll
ping you when you need to rebase.

**Comment by tubbo** [comment]
@thedrow ok I just fixed 'master', please rebase this branch when you get a chance.

**Comment by thedrow** [comment]
Done :)

**Comment by tubbo** [comment]
@thedrow can you have a look at https://travis-ci.org/redis-store/redis-store/jobs/150533555? only seems to fail on 2.0.0 for some reason...

**Comment by thedrow** [comment]
It doesn't look like I did something wrong.

**Comment by tubbo** [comment]
@thedrow can you reproduce locally?

**Comment by thedrow** [comment]
I'll give it a shot

**Comment by tubbo** [comment]
@thedrow who knows why it was failing but it seems to work now. thanks!

**Pull request merged**
