### PR TITLE
Specifying default cache options no longer accidentally creates a DistributedStore (Fix for #166)

### PR DESCRIPTION
**Pull request by mjtko**
This pull request includes the failing tests created in #166, along with a fix which makes the tests pass.

This patch causes the options to be extracted from the addresses arguments passed in to `Store#initialize` prior to calling the `Redis::Factory::create` method.

### CODE REVIEW

**Comment by radar** [comment]
Can this PR please be updated to be mergeable to master?

**Comment by mjtko** [comment]
Doesn't look straightforward to update this given all the structural changes.  Are we sure this is even still an issue in the latest version/layout of `redis-store`?

**Comment by mjtko** [comment]
It's been a while since I've looked at this obviously -- this needs to be updated to be a PR against `redis-activesupport` now then, right?

**Comment by mjtko** [comment]
Superceded PR against `redis-activesupport`: redis-store/redis-activesupport#29.  Closing this one.

**Comment by mjtko** [comment]
(PS. thanks for getting on top of this @radar!)

**Comment by radar** [comment]
No worries :) Thanks for the patch.

**Pull request closed without merging**
