### PR TITLE
Namespace zincrby and zscore

### PR DESCRIPTION
**Pull request by psparrow**
This PR adds namespace support to `zincrby` and `zscore`.

### CODE REVIEW

**Comment by psparrow** [comment]
> Lookin' good! Thanks @psparrow

Thanks! I'll likely add a few more methods to the Namespace module soon to cover more of the sorted set methods.

**Comment by tubbo** [comment]
Cool, I’ll wait to release this until you add those methods.

**Comment by psparrow** [comment]
@tubbo I didn't end up having to add more sorted set methods. Any chance of pushing a release out soon?

**Comment by psparrow** [comment]
@tubbo Actually, I just had to add `zrem` and `zadd`. I'll PR those and then a release may be in order. :)

**Comment by tubbo** [comment]
@psparrow releasing all this as **v1.8.2**

**Pull request merged**
