### PR TITLE
fix inefficient use of KEYS when calling FLUSHDB if namespace is nil

### PR DESCRIPTION
**Pull request by ccutrer**

### CODE REVIEW

**Comment by tubbo** [comment]
@ccutrer now that it's in master...would it be possible for you to give this a solid test?

```ruby
gem 'redis-store', github: 'redis-store/redis-store'
```

**Comment by ccutrer** [comment]
@tubbo: yeah, give me a few minutes to write a test. you merged so fast I was confused because GitHub is still offering to Compare & Pull, but there are no changes!

**Comment by ccutrer** [comment]
oh hey, I see you mean do a manual integration test. I had already done that locally before I pushed the PR. but there's another PR with automated tests, too now!

**Comment by tubbo** [comment]
@ccutrer I actually just meant a quick manual test, like try to clear cache on a QA server and make sure it doesn't blow up, but yeah I usually require tests along with the PR. for next time :)

**Comment by jasim** [comment]
@tubbo Hey! we were getting slow queries when flushing our cache and saw that it was fixed in this PR. I've just deployed redis-store master to our staging server so that we can run it for a while and report back any issues. Do you have any timelines on releasing a new version and is there anything I can help with? Thanks!

**Comment by tubbo** [comment]
I was going to release a new version either Monday or Tuesday of next week, if everything goes well and @ccutrer has no objections :)

**Comment by ccutrer** [comment]
No objections from me. We've been running off of essentially the master branch in prod for ~4 months now.

**Comment by jasim** [comment]
@ccutrer @tubbo Thanks! We've put this on our staging environment a few days ago. Things are looking great, once you release we'll move over production as well.

**Comment by tubbo** [comment]
ok folks, redis-store 1.5.0 is [out on rubygems](https://rubygems.org/gems/redis-store) :) 

you can use it like so:

```ruby
group :production do
  gem 'redis-rails'
  gem 'redis-rack-cache'
  gem 'redis-store', '~> 1.5'
end
```

all the other redis-store gems can depend on any version of redis-store as long as there are no breaking changes, e.g. we release a 2.0 at some point.

let me know if there are any issues. thanks for your contributions!

**Comment by jasim** [comment]
@tubbo We've been running this in production for a few days now, everything is great so far. Thanks!

**Pull request merged**
