### PR TITLE
Add support for setex and ttl to namespace

### PR DESCRIPTION
**Pull request by soupmatt**

### CODE REVIEW

**Comment by radar** [comment]
Hi @raphi or @soupmatt. Can you please rebase this PR on top of master? I can then merge it in.

**Comment by soupmatt** [comment]
rebase done

**Comment by radar** [comment]
Thanks @soupmatt. Looks good to me :)

**Comment by mezis** [comment]
Any chance we can get a 1.1.5 release with this?
Without this diff, `redis-rack-cache` breaks with `use_native_ttl`.

**Comment by radar** [comment]
I will look into doing a release today.

**Comment by radar** [comment]
redis-store@1.1.5 has been released :) Thanks for the prompt, @mezis.

**Comment by mezis** [comment]
You're very welcome @radar ^_^

**Pull request merged**
